import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Footer from "./footer/footer";
import ReduxProvider from "@/providers/reduxProvieder";
import { Directions, Languages } from "@/constants/enums";
import { Locale } from "@/i18n.config";

const roboto = Roboto({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
  preload: true,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return [{ locale: Languages.ENGLISH }, { locale: Languages.ARABIC }];
}

export default async function RootLayout({
  params,
  children,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: Locale }>;
}>) {
  const locales = (await params).locale;
  return (
    <html
      lang={locales}
      dir={locales === Languages.ARABIC ? Directions.RTL : Directions.LTR}>
      <body className={roboto.className}>
        <ReduxProvider>
          <Header />
          <main>{children}</main>
          <Footer />
        </ReduxProvider>
      </body>
    </html>
  );
}
